# Generated by Django 3.2.7 on 2021-09-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.IntegerField(default=0, unique=True)),
                ('category_name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True)),
                ('category_icon', models.ImageField(blank=True, default='category_icon', upload_to='', verbose_name='Category Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Studio')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_number', models.IntegerField(default=0, unique=True)),
                ('option_name', models.CharField(max_length=255, verbose_name='Option Name')),
                ('slug', models.SlugField(unique=True)),
                ('option_icon', models.ImageField(blank=True, default='option_icon', upload_to='', verbose_name='Icon')),
                ('comment', models.CharField(blank=True, max_length=254, null=True, verbose_name='Comment')),
                ('specification_url', models.URLField(blank=True, null=True)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price')),
                ('daily_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_potions', to='plans.category')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254, verbose_name='Product Name')),
                ('slug', models.SlugField(unique=True)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Discount')),
                ('image_1', models.ImageField(blank=True, upload_to='image', verbose_name='Image One')),
                ('image_2', models.ImageField(blank=True, upload_to='image', verbose_name='Image Two')),
                ('image_3', models.ImageField(blank=True, upload_to='image', verbose_name='Image Three')),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
                ('review', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Review')),
                ('offer', models.CharField(blank=True, max_length=254, null=True, verbose_name='Offer')),
                ('comment', models.CharField(blank=True, max_length=254, null=True, verbose_name='Comment')),
                ('details', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Details')),
                ('how_to_use', models.TextField(blank=True, max_length=1000, null=True, verbose_name='How to use')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='plans.category')),
                ('option', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.option', verbose_name='Option')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plans.time', verbose_name='Set Time')),
                ('space', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spaces.space', verbose_name='Space')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
