# Generated by Django 3.2.7 on 2021-09-26 09:03

from django.db import migrations, models
import django.db.models.deletion
import utils.image_upload_helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_option_image_path)),
                ('comment', models.CharField(blank=True, max_length=254, null=True)),
                ('specification_url', models.URLField(blank=True, null=True)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('daily_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('slug', models.SlugField(unique=True)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('daily_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_plan_image_path)),
                ('image_1_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('image_1_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_plan_image_path)),
                ('image_2_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('image_2_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_plan_image_path)),
                ('image_3_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('image_3_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('explanatory_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_options', to='plans.option')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_plans', to='spaces.space')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_category_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='stores.store')),
            ],
            options={
                'verbose_name': 'Option Category',
                'verbose_name_plural': 'Option Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='option',
            name='option_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_category_options', to='plans.optioncategory'),
        ),
    ]
