# Generated by Django 3.2.7 on 2021-09-26 08:12

from django.db import migrations, models
import django.db.models.deletion
import utils.image_upload_helper


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_space_store'),
        ('stores', '0002_store_studio'),
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_category_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='stores.store')),
            ],
            options={
                'verbose_name': 'Option Category',
                'verbose_name_plural': 'Option Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('slug', models.SlugField(unique=True)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('daily_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_plan_image_path)),
                ('image_1_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('image_1_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_plan_image_path)),
                ('image_2_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('image_2_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_plan_image_path)),
                ('image_3_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('image_3_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('explanatory_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='space',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.RemoveField(
            model_name='time',
            name='store',
        ),
        migrations.RemoveField(
            model_name='option',
            name='category',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_icon',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_name',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_number',
        ),
        migrations.AddField(
            model_name='option',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_option_image_path),
        ),
        migrations.AddField(
            model_name='option',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='title',
            field=models.CharField(default='example', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='comment',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='option',
            name='hourly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='option',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AddField(
            model_name='plan',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_options', to='plans.option'),
        ),
        migrations.AddField(
            model_name='plan',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_plans', to='spaces.space'),
        ),
        migrations.AddField(
            model_name='option',
            name='option_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='option_category_options', to='plans.optioncategory'),
            preserve_default=False,
        ),
    ]
