# Generated by Django 3.2.7 on 2021-09-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('country_code', models.CharField(default='JP', max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_calendar', to='studios.studio')),
            ],
            options={
                'verbose_name': 'Studio Calendar',
                'verbose_name_plural': 'Studio Calendars',
                'ordering': ['-created_at'],
            },
        ),
    ]
