# Generated by Django 3.2.7 on 2021-09-23 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('furigana', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_person_in_charge', models.PositiveIntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('prefecture', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('building_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=254, null=True)),
                ('other_contact_information', models.CharField(blank=True, max_length=254, null=True)),
                ('identification', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Already'), (1, 'Yet')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
