# Generated by Django 3.2.7 on 2021-09-24 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studio_user', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiomoderator',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studio_moderator', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studiomoderator',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Studio', to='studios.studio'),
        ),
    ]
