# Generated by Django 3.2.7 on 2021-09-26 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studios', '0002_auto_20210924_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiomoderator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio_moderator_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
