# Generated by Django 3.2.7 on 2021-09-26 06:09

from django.db import migrations, models
import django.db.models.deletion
import utils.image_upload_helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('contact_1', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_2', models.CharField(blank=True, max_length=30, null=True)),
                ('explanatory_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('google_map', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_store_image_path)),
                ('image_1_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('image_1_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_store_image_path)),
                ('image_2_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('image_2_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helper.upload_store_image_path)),
                ('image_3_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('image_3_comment', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_stores', to='studios.studio')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['-created_at'],
            },
        ),
    ]
